package money

import "golang.org/x/text/language"

// FormatOptions defines how monetary amounts should be formatted
type FormatOptions struct {
	Symbol       string // Currency symbol (e.g., "$", "€")
	SymbolFirst  bool   // Whether to place the symbol before the amount
	ThousandsSep string // Thousands separator (e.g., ",", ".")
	DecimalSep   string // Decimal separator (e.g., ".", ",")
	SpaceBetween bool   // Whether to add space between amount and symbol
	ShowCurrency bool   // Whether to show the currency code (e.g., "USD")
	MinDigits    int    // Minimum fraction digits
	MaxDigits    int    // Maximum fraction digits
}

// Currency represents a currency configuration
type Currency struct {
	Code          string       // ISO 4217 code
	Scale         int          // Number of decimal places
	Tag           language.Tag // Language/region tag for formatting
	DefaultFormat FormatOptions
}

var Currencies = map[string]Currency{
	"USD": {Code: "USD", Scale: 2, Tag: language.AmericanEnglish,
		DefaultFormat: FormatOptions{
			Symbol:       "$",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"EUR": {Code: "EUR", Scale: 2, Tag: language.German, // default to German locale
		DefaultFormat: FormatOptions{
			Symbol:       "€",
			SymbolFirst:  true,
			ThousandsSep: ".",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"JPY": {Code: "JPY", Scale: 0, Tag: language.Japanese,
		DefaultFormat: FormatOptions{
			Symbol:       "¥",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    0,
			MaxDigits:    0,
		},
	},
	"INR": {Code: "INR", Scale: 2, Tag: language.Hindi,
		DefaultFormat: FormatOptions{
			Symbol:       "₹",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"GBP": {Code: "GBP", Scale: 2, Tag: language.BritishEnglish,
		DefaultFormat: FormatOptions{
			Symbol:       "£",
			SymbolFirst:  true,
			ThousandsSep: ",", // British English uses comma as thousands separator
			DecimalSep:   ".", // British English uses dot as decimal separator
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"CNY": {Code: "CNY", Scale: 2, Tag: language.SimplifiedChinese,
		DefaultFormat: FormatOptions{
			Symbol:       "¥",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"RUB": {Code: "RUB", Scale: 2, Tag: language.Russian,
		DefaultFormat: FormatOptions{
			Symbol:       "₽",
			SymbolFirst:  false,
			ThousandsSep: " ",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"KRW": {Code: "KRW", Scale: 0, Tag: language.Korean,
		DefaultFormat: FormatOptions{
			Symbol:       "₩",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    0,
			MaxDigits:    0,
		},
	},
	"AUD": {Code: "AUD", Scale: 2, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "$",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"MXN": {Code: "MXN", Scale: 2, Tag: language.Spanish,
		DefaultFormat: FormatOptions{
			Symbol:       "$",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"CAD": {Code: "CAD", Scale: 2, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "$",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"BRL": {Code: "BRL", Scale: 2, Tag: language.Portuguese,
		DefaultFormat: FormatOptions{
			Symbol:       "R$",
			SymbolFirst:  true,
			ThousandsSep: ".",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"ZAR": {Code: "ZAR", Scale: 2, Tag: language.Afrikaans,
		DefaultFormat: FormatOptions{
			Symbol:       "R",
			SymbolFirst:  true,
			ThousandsSep: " ",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"NZD": {Code: "NZD", Scale: 2, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "$",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"SEK": {Code: "SEK", Scale: 2, Tag: language.Swedish,
		DefaultFormat: FormatOptions{
			Symbol:       "kr",
			SymbolFirst:  false,
			ThousandsSep: " ",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"CHF": {Code: "CHF", Scale: 2, Tag: language.German,
		DefaultFormat: FormatOptions{
			Symbol:       "CHF",
			SymbolFirst:  false,
			ThousandsSep: "'",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"TRY": {Code: "TRY", Scale: 2, Tag: language.Turkish,
		DefaultFormat: FormatOptions{
			Symbol:       "₺",
			SymbolFirst:  true,
			ThousandsSep: ".",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"SGD": {Code: "SGD", Scale: 2, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "$",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"NOK": {Code: "NOK", Scale: 2, Tag: language.Norwegian,
		DefaultFormat: FormatOptions{
			Symbol:       "kr",
			SymbolFirst:  false,
			ThousandsSep: " ",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"IDR": {Code: "IDR", Scale: 2, Tag: language.Indonesian},
	"MYR": {Code: "MYR", Scale: 2, Tag: language.Malay},
	"PHP": {Code: "PHP", Scale: 2, Tag: language.Filipino},
	"THB": {Code: "THB", Scale: 2, Tag: language.Thai},
	"VND": {Code: "VND", Scale: 0, Tag: language.Vietnamese},
	"PLN": {Code: "PLN", Scale: 2, Tag: language.Polish,
		DefaultFormat: FormatOptions{
			Symbol:       "zł",
			SymbolFirst:  false,
			ThousandsSep: " ",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"RON": {Code: "RON", Scale: 2, Tag: language.Romanian},
	"UAH": {Code: "UAH", Scale: 2, Tag: language.Ukrainian},
	"ILS": {Code: "ILS", Scale: 2, Tag: language.Hebrew},
	"HUF": {Code: "HUF", Scale: 2, Tag: language.Hungarian},
	"CZK": {Code: "CZK", Scale: 2, Tag: language.Czech,
		DefaultFormat: FormatOptions{
			Symbol:       "Kč",
			SymbolFirst:  false,
			ThousandsSep: " ",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"CLP": {Code: "CLP", Scale: 0, Tag: language.Spanish,
		DefaultFormat: FormatOptions{
			Symbol:       "$",
			SymbolFirst:  true,
			ThousandsSep: ".",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    0,
			MaxDigits:    0,
		},
	},
	"COP": {Code: "COP", Scale: 2, Tag: language.Spanish},
	"ARS": {Code: "ARS", Scale: 2, Tag: language.Spanish},
	"PEN": {Code: "PEN", Scale: 2, Tag: language.Spanish},
	"EGP": {Code: "EGP", Scale: 2, Tag: language.Arabic},
	"KES": {Code: "KES", Scale: 2, Tag: language.Swahili},
	"NGN": {Code: "NGN", Scale: 2, Tag: language.English},
	"ZMW": {Code: "ZMW", Scale: 2, Tag: language.English},
	"UGX": {Code: "UGX", Scale: 2, Tag: language.English},
	"TZS": {Code: "TZS", Scale: 2, Tag: language.English},
	"GHS": {Code: "GHS", Scale: 2, Tag: language.English},
	"RWF": {Code: "RWF", Scale: 0, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "RF",
			SymbolFirst:  false,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    0,
			MaxDigits:    0,
		},
	},
	"MWK": {Code: "MWK", Scale: 2, Tag: language.English},
	"ZMK": {Code: "ZMK", Scale: 2, Tag: language.English},
	"XAF": {Code: "XAF", Scale: 0, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "FCFA",
			SymbolFirst:  false,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    0,
			MaxDigits:    0,
		},
	},
	"XOF": {Code: "XOF", Scale: 0, Tag: language.English},
	"XCD": {Code: "XCD", Scale: 2, Tag: language.English},
	"XPF": {Code: "XPF", Scale: 0, Tag: language.English},
	"VUV": {
		Code: "VUV", Scale: 0, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "VT",
			SymbolFirst:  false,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    0,
			MaxDigits:    0,
		},
	},
	"KWD": {Code: "KWD", Scale: 3, Tag: language.Arabic,
		DefaultFormat: FormatOptions{
			Symbol:       "د.ك.",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    3,
			MaxDigits:    3,
		},
	},
	"SAR": {Code: "SAR", Scale: 2, Tag: language.Arabic,
		DefaultFormat: FormatOptions{
			Symbol:       "ر.س",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"AED": {Code: "AED", Scale: 2, Tag: language.Arabic,
		DefaultFormat: FormatOptions{
			Symbol:       "د.إ",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"QAR": {Code: "QAR", Scale: 2, Tag: language.Arabic,
		DefaultFormat: FormatOptions{
			Symbol:       "ر.ق",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"OMR": {Code: "OMR", Scale: 3, Tag: language.Arabic,
		DefaultFormat: FormatOptions{
			Symbol:       "ر.ع.",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    3,
			MaxDigits:    3,
		},
	},
	"BHD": {
		Code: "BHD", Scale: 3, Tag: language.Arabic,
		DefaultFormat: FormatOptions{
			Symbol:       "د.ب.",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    3,
			MaxDigits:    3,
		},
	},
	"JOD": {
		Code: "JOD", Scale: 3, Tag: language.Arabic,
		DefaultFormat: FormatOptions{
			Symbol:       "د.ا.",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    3,
			MaxDigits:    3,
		},
	},
	"LYD": {
		Code: "LYD", Scale: 3, Tag: language.Arabic,
		DefaultFormat: FormatOptions{
			Symbol:       "د.ل.",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    3,
			MaxDigits:    3,
		},
	},
	"YER": {Code: "YER", Scale: 2, Tag: language.Arabic,
		DefaultFormat: FormatOptions{
			Symbol:       "﷼",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"SDG": {Code: "SDG", Scale: 2, Tag: language.Arabic,
		DefaultFormat: FormatOptions{
			Symbol:       "ج.س.",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"SSP": {Code: "SSP", Scale: 2, Tag: language.Arabic},
	"MRU": {Code: "MRU", Scale: 2, Tag: language.Arabic},
	"BYN": {Code: "BYN", Scale: 2, Tag: language.Russian},
	"AMD": {Code: "AMD", Scale: 2, Tag: language.Armenian},
	"AZN": {Code: "AZN", Scale: 2, Tag: language.Azerbaijani},
	"KZT": {Code: "KZT", Scale: 2, Tag: language.Kazakh},
	"KGS": {Code: "KGS", Scale: 2, Tag: language.Kirghiz},
	"TJS": {Code: "TJS", Scale: 2, Tag: language.Uzbek}, // Tajikistani somoni, language is Uzbek
	"UZS": {Code: "UZS", Scale: 2, Tag: language.Uzbek},
	"AFN": {Code: "AFN", Scale: 2, Tag: language.English}, // Afghani, language is English
	"PKR": {Code: "PKR", Scale: 2, Tag: language.Urdu},
	"RSD": {
		Code: "RSD", Scale: 2, Tag: language.Serbian,
		DefaultFormat: FormatOptions{
			Symbol:       "din",
			SymbolFirst:  false,
			ThousandsSep: ".",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"MKD": {
		Code: "MKD", Scale: 2, Tag: language.Macedonian,
		DefaultFormat: FormatOptions{
			Symbol:       "ден",
			SymbolFirst:  false,
			ThousandsSep: ".",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"ALL": {Code: "ALL", Scale: 2, Tag: language.Albanian},
	"BAM": { // Convertible mark, language is Serbian
		Code: "BAM", Scale: 2, Tag: language.Serbian,
		DefaultFormat: FormatOptions{
			Symbol:       "KM",
			SymbolFirst:  true,
			ThousandsSep: ".",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"HRK": {
		Code: "HRK", Scale: 2, Tag: language.Croatian,
		DefaultFormat: FormatOptions{
			Symbol:       "kn",
			SymbolFirst:  false,
			ThousandsSep: ".",
			DecimalSep:   ",",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    2,
			MaxDigits:    2,
		},
	},
	"BGN": {Code: "BGN", Scale: 2, Tag: language.Bulgarian},

	// major crypto currencies
	"BTC": {
		Code: "BTC", Scale: 8, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "₿",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    8,
			MaxDigits:    8,
		},
	},
	"ETH": {Code: "ETH", Scale: 18, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "Ξ",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    18,
			MaxDigits:    18,
		},
	},
	"LTC": {Code: "LTC", Scale: 8, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "Ł",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    8,
			MaxDigits:    8,
		},
	},
	"XRP": {Code: "XRP", Scale: 6, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "Ʀ",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    6,
			MaxDigits:    6,
		},
	},
	"XMR": {Code: "XMR", Scale: 12, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "ɱ",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    12,
			MaxDigits:    12,
		},
	},
	"SOL": {Code: "SOL", Scale: 9, Tag: language.English,
		DefaultFormat: FormatOptions{
			Symbol:       "S◎L",
			SymbolFirst:  true,
			ThousandsSep: ",",
			DecimalSep:   ".",
			SpaceBetween: true,
			ShowCurrency: false,
			MinDigits:    9,
			MaxDigits:    9,
		},
	},
}
